version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: orchid-orm
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
